### ISSUE TITLE
 Call to undefined method Icarus_Widget_Aside::printStickyByPos() 

### ISSUE THREAD

**Issue by bsed** [KeNorizon/typecho-theme-icarus#1] opened 2019-01-21 01:42 UTC
![default](https://user-images.githubusercontent.com/10845087/51448317-ce7ee780-1d60-11e9-9ac7-a3201e62b31c.png)

**Comment by imkero** [comment] 2019-01-21 09:28
I'm sorry that this theme project is currently under construction and may not work properly.
The problem you met is caused by a spelling mistake taken in the commit [dc07a35](https://github.com/KeNorizon/typecho-theme-icarus/commit/dc07a35614c713791db7e0e33942bdd2dc27fd19#diff-18bb81bb3c73a7ccf1e3cad3a55d2fc4R105), and I had it fixed in the following commit d394985346c2d303d6af123b5b9164ac4e342042.
You can get the latest build of this theme by clicking the [Download Zip] button, which is working good but still lacking of some necessary functions. (e.g. still missing comments of posts)
But I suggest that you can watch this repo and wait for its stable release soon.
Thank you.

**Closed as completed by imkero** 2019-01-21 09:28 UTC
Labels: bug
